# Generated by Django 3.1.5 on 2021-04-24 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Area",
            fields=[
                ("area_id", models.IntegerField(primary_key=True, serialize=False)),
                ("town_name", models.CharField(max_length=15, null=True)),
                ("district_name", models.CharField(max_length=15, null=True)),
                ("address_name", models.CharField(max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="GarbageType",
            fields=[
                (
                    "garbage_type",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("garbage_name", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Remind",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.CharField(max_length=64)),
                ("when2push", models.DateField(auto_now=True)),
                (
                    "garbage_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="garbage_bot.garbagetype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Context",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_id", models.CharField(max_length=64)),
                ("state", models.IntegerField()),
                ("area_candidates", models.JSONField(null=True)),
                ("optional", models.JSONField(null=True)),
                ("uuid", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "garbage_type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="garbage_bot.garbagetype",
                    ),
                ),
            ],
            options={
                "get_latest_by": ["updated_at"],
            },
        ),
        migrations.CreateModel(
            name="CollectDay",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("weekday_info", models.CharField(max_length=10)),
                ("nth_week", models.IntegerField()),
                ("day_or_night", models.IntegerField()),
                (
                    "area_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="garbage_bot.area",
                    ),
                ),
                (
                    "garbage_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="garbage_bot.garbagetype",
                    ),
                ),
            ],
        ),
    ]
