# Generated by Django 3.1.5 on 2021-04-24 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("garbage_bot", "0002_auto_20210424_1455"),
    ]

    operations = [
        migrations.AlterField(
            model_name="area",
            name="district_name",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="area",
            name="town_name",
            field=models.CharField(max_length=64, null=True),
        ),
    ]
