version: "3.8"
   
services:
  db:
    image: postgres
    volumes:
      - .postgres/:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code

    ports:
      - "127.0.0.1:8000:8000"
    environment:
      # DATABASE_URL="postgres://username:password@hostname:5432/database"
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
    env_file:
      - .env

    # よく分からないのであとで勉強する
    # https://qiita.com/NagaokaKenichi/items/7b66c58fda36b46f5938
    # tty: true
    # stdin_open: true
    depends_on:
      - db