# Generated by Django 3.1.5 on 2021-03-23 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garbage_bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectday',
            name='weekday_info',
            field=models.CharField(max_length=10),
        ),
    ]
