# This is a basic workflow to help you get started with Actions
name: docker-compose

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: compose-run
        shell: bash
        env:
          LINE_TEST_UID: ${{ secrets.LINE_TEST_UID }}
          LINE_ACCESS_TOKEN: ${{ secrets.LINE_ACCESS_TOKEN }}
          LINE_CHANNEL_SECRET: ${{ secrets.LINE_CHANNEL_SECRET }}
          # UID_INCLUDED_JSON_FILE: ${{ secrets.UID_INCLUDED_JSON_FILE }}
        run: |
          cd ./mybot
          echo $LINE_TEST_UID\n$LINE_ACCESS_TOKEN\n$LINE_CHANNEL_SECRET\nUID_INCLUDED_JSON_FILE > .env
          docker-compose up -d
          docker-compose exec web python manage.py migrate
          docker-compose exec web python manage.py test
